export const WORK_ITEMS = [
  //
  //  DESIGN PROJECTS
  {
    file: 'assets/my_works/design-img/D12 (1).jpg',
    title: 'Massage center menu card page 1',
    description: 'A clean and different menu card for client.',
    link: null,
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (2).jpg',
    title: 'Massage center menu card page 2',
    description: 'A clean and different menu card for client.',
    link: null,
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (3).jpg',
    title: 'Massage center menu card page 1',
    description: 'A clean and different menu card for client.',
    link: null,
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (4).jpg',
    title: 'Massage center menu card page 2',
    description: 'A clean and different menu card for client.',
    link: null,
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (5).jpg',
    title: 'Poster for Nuts Gallery',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: null,
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (6).jpg',
    title: 'Poster for Nuts Gallery',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (7).jpg',
    title: 'Poster for Nuts Gallery',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (8).jpg',
    title: 'Banner for Express Evenue',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (9).jpg',
    title: 'Banner for Express Evenue',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (10).jpg',
    title: 'Banner for Express Evenue',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (11).jpg',
    title: 'Banner for Express Evenue',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (12).jpg',
    title: 'Banner for Express Evenue',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (13).jpg',
    title: 'Banner for Express Evenue',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (14).jpg',
    title: 'Banner for Express Evenue',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (15).jpg',
    title: 'Banner for Express Evenue',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (16).jpg',
    title: 'Banner for Express Evenue',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (17).jpg',
    title: 'Banner for Express Evenue',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (18).jpg',
    title: 'Banner for Express Evenue',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (19).jpg',
    title: 'Poster for EHOTEL',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (20).jpg',
    title: 'Poster for EHOTEL',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (21).jpg',
    title: 'Poster for Express Evenue',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (22).jpg',
    title: 'Poster for Express Evenue',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (23).jpg',
    title: 'Poster for EHOTEL',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (24).jpg',
    title: 'Poster for EHOTEL',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (25).jpg',
    title: 'CREDORA logo design 1',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (26).jpg',
    title: 'CREDORA logo design 2',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (27).jpg',
    title: 'Self promotion poster',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (28).jpg',
    title: 'Selp promotion banner',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (29).jpg',
    title: 'Broucher for CREDORA',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (30).jpg',
    title: 'Poster for EHOTEL',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (31).jpg',
    title: 'Poster for EHOTEL',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (32).jpg',
    title: 'Arch Banner for Express Evenue',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (33).jpg',
    title: 'Poster for Express Evenue',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (34).jpg',
    title: 'Poster for EHOTEL',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (34).jpg',
    title: 'Poster for EHOTEL',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (35).jpg',
    title: 'Poster for Express Evenue',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (36).jpg',
    title: 'Poster for Nuts Gallery',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (37).jpg',
    title: 'Poster for Nuts Gallery',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (38).jpg',
    title: 'Poster for Nuts Gallery',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (39).jpg',
    title: 'Poster for Nuts Gallery',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (40).jpg',
    title: 'Poster for Nuts Gallery',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (41).jpg',
    title: 'Poster for Nuts Gallery',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (42).jpg',
    title: 'Poster for Nuts Gallery',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (43).jpg',
    title: 'Poster for Nuts Gallery',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/design-img/D12 (44).jpg',
    title: 'Poster for Nuts Gallery',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/pfd/PDF1 (1).pdf',
    title: 'Ad Campaign Promo',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/pfd/PDF1 (2).pdf',
    title: 'Ad Campaign Promo',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/pfd/PDF1 (3).pdf',
    title: 'Ad Campaign Promo',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/pfd/PDF1 (4).pdf',
    title: 'Ad Campaign Promo',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/pfd/PDF1 (5).pdf',
    title: 'Ad Campaign Promo',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/pfd/PDF1 (6).pdf',
    title: 'Ad Campaign Promo',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/pfd/PDF1 (7).pdf',
    title: 'Ad Campaign Promo',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/pfd/PDF1 (8).pdf',
    title: 'Ad Campaign Promo',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/pfd/PDF1 (9).pdf',
    title: 'Ad Campaign Promo',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/pfd/PDF1 (10).pdf',
    title: 'Ad Campaign Promo',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/pfd/PDF1 (11).pdf',
    title: 'Ad Campaign Promo',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/pfd/PDF1 (12).pdf',
    title: 'Ad Campaign Promo',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },
  {
    file: 'assets/my_works/pfd/PDF1 (13).pdf',
    title: 'Ad Campaign Promo',
    description: 'High-energy motion graphic ad for social campaigns.',
    link: 'https://example.com/ad-promo',
    category: 'design',
  },

  //
  //
  //  ANGULAR PROJECTS
  {
    file: '../../assets/Angular_Logo-01.png',
    title: 'Calculator',
    description:
      'A basic Angular calculator that performs addition, subtraction, multiplication, and division with a clean UI and instant results.',
    link: 'https://ramakrishna-me.github.io/calculator',
    category: 'angular',
    // image: 'assets/Angular_Logo.gif',
  },
  {
    file: 'assets/Angular_Logo.gif',
    title: 'E-Commerce',
    description:
      'A product browsing system with filters, sorting, wishlist, cart, recently viewed items, price discounts, and product compare features all powered by Angular.',
    link: 'https://ramakrishna-me.github.io/e-commerce/',
    category: 'angular',
    // image: 'assets/Angular_Logo.gif',
  },
  {
    file: 'assets/Angular_Logo.gif',
    title: 'Social Media app',
    description:
      'A full-screen social feed where users can create posts, upload images, react with emojis, comment, view stories, and switch between light/dark modes.',
    link: 'https://ramakrishna-me.github.io/social/',
    category: 'angular',
    // image: 'assets/Angular_Logo.gif',
  },
  {
    file: 'assets/Angular_Logo.gif',
    title: 'Dynamic Form Builder',
    description:
      'A modern Angular 20 app to visually build forms with drag-and-drop, validation, and real-time preview.',
    link: 'https://ramakrishna-me.github.io/dynamic_form_builder/',
    category: 'angular',
    // image: 'assets/Angular_Logo.gif',
  },
  //
  //
  //
  //
  // FIGMA PROJECTS
  {
    file: 'assets/my_works/figma_app_ui.png',
    title: 'Figma Mobile App UI Kit',
    description: 'Clean and consistent UI kit built for Figma community.',
    link: 'https://figma.com/file/12345',
    category: 'figma',
  },
  {
    file: 'assets/my_works/figma_dashboard.png',
    title: 'Admin Dashboard Design',
    description: 'Dark-mode Figma layout for SaaS analytics dashboard.',
    link: 'https://figma.com/file/67890',
    category: 'figma',
  },
  {
    file: 'assets/my_works/ux_report.pdf',
    title: 'UX Research Report',
    description: 'Case study on improving onboarding flow with user testing.',
    link: 'https://example.com/ux-report',
    category: 'figma',
  },
];
